backend:
  name: bitbucket
  repo: indigomelody/globelynx_netlifycms
  branch: emman_v1
  accept_roles:
    - admin
    - editor
  
media_folder: static/img
public_folder: /img

collections:
  - name: "news"
    label: "News"
    folder: "src/pages/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "news-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
  - name: "camerasDetails"
    label: "Cameras Details"
    folder: "src/pages/camerasDetails"
    create: true
    slug: "Cameras-{{slug}}"
    identifier_field: name
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "cameras-details"}
      - {label: "CamerasImage", name: "camerasimage", widget: "image"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Details", name: "details", widget: "string"}
      - {label: "Recorder", name: "recorder", widget: "string"}
      - {label: "Frame", name: "frame", widget: "string"}
      - {label: "Weight", name: "weight", widget: "string"}
      - {label: "Portable", name: "portable", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/home/index.md"
        label: "Home"
        name: "home"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "home-page"}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Mid_banner, name: mid_banner, widget: image}
          - {label: Featured_experts, name: featured_experts, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Experts, name: experts, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Recent_bookings, name: recent_bookings, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Bookings, name: bookings, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Current_topics, name: current_topics, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Topics, name: topics, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Low_banner, name: low_banner, widget: image}
          - {label: Basic_info, name: basic_info, widget: string}
          - {label: Basic_description, name: basic_description, widget: string}
          - {label: Work_process, name: work_process, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Works, name: works, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Heading_one, name: heading_one, widget: string}
          - {label: Description_one, name: description_one, widget: string}
          - {label: Heading_two, name: heading_two, widget: string}
          - {label: Description_two, name: description_two, widget: string}
      - file: "src/pages/products/index.md"
        label: "Products"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "products-page"}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Heading_one, name: heading_one, widget: string}
          - {label: Description_one, name: description_one, widget: string}
          - {label: Heading_two, name: heading_two, widget: string}
          - {label: Description_two, name: description_two, widget: string}
          - {label: Heading_three, name: heading_three, widget: string}
          - {label: Description_three, name: description_three, widget: string}
          - {label: Heading_four, name: heading_four, widget: string}
          - {label: Description_four, name: description_four, widget: string}
          - {label: Heading_five, name: heading_five, widget: string}
          - {label: Description_five, name: description_five, widget: string}
          - {label: Products_images, name: products_images, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Product, name: product, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
      - file: "src/pages/cameras/index.md"
        label: "Cameras"
        name: "cameras"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "cameras-page"}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Camera_images, name: camera_images, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Camera, name: camera, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
      - file: "src/pages/contact/index.md"
        label: "Contact"
        name: "contact"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "contact-page"}
          - {label: Heading_one, name: heading_one, widget: string}
          - {label: Description_one, name: description_one, widget: string}
          - {label: Heading_two, name: heading_two, widget: string}
          - {label: Description_two, name: description_two, widget: string}
          - {label: Heading_three, name: heading_three, widget: string}
          - {label: Description_three, name: description_three, widget: string}
